PATHS:
  src: "./_src"
  tmp: "./.tmp"
  dest: "./dist"

  css: "css"
  js: "js"
  images: "img"
  hugo: "hugo"

TASKS:
  browserSync:
  css:
    extensions:
      - "scss"
      - "css"
    sass:
      indentedSyntax: false
      includePaths":
  js:
    extensions:
      - "js"
  images:
    extensions:
      - "jpg"
      - "png"
      - "gif"
      - "svg"
